version: "3.9"

services:
    postgres:
        image: postgres:alpine
        hostname: postgres
        ports:
            - 5433:5432
        environment: 
            POSTGRES_PASSWORD: foreverbull
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

